name: epanty_mobility
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.4+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter

  cloud_firestore: ^3.1.11
  firebase_auth: ^3.3.12
  flutter:
    sdk: flutter
  form_field_validator: ^1.1.0
  google_fonts: ^2.3.1
  provider: ^6.0.2
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.13
  firebase_core: ^1.14.0
  google_maps_flutter: ^2.1.3
  location: ^4.3.0
  geocoding: ^2.0.4
  google_directions_api: ^0.9.1
  flutter_polyline_points: ^1.0.0
  geolocator: ^8.2.0
  image_picker: ^0.8.5
  firebase_storage: ^10.2.10
  dio: ^4.0.6
  http: ^0.13.4
  shimmer: ^2.0.0
  uuid: ^3.0.6
  rflutter_alert: ^2.0.4
  flash: ^2.0.3+2
  progress_indicator_button: ^0.0.3
  flutterwave: ^1.0.1
  flutter_compass: ^0.7.0
  intl: ^0.17.0
  animations: ^2.0.2
  url_launcher: ^6.0.20
  path_provider: ^2.0.9
  mailer: ^5.1.0
  google_sign_in: ^5.2.0
  fluttertoast: ^8.0.9
  cupertino_icons:
  flutter_facebook_auth: ^3.4.1
  flutter_background_service: ^2.0.0
  currency_pickers: ^1.0.6
  money_converter: ^2.0.1
  states_rebuilder: ^1.9.0
  change_app_package_name: ^0.1.3
  http_auth: ^1.0.1
  flutter_email_sender: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.3+1

flutter_native_splash:
  background_image: "assets/images/Epanty Acceuil.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/tab/
    - assets/images/
    - assets/images/payment/
    - assets/images/auth/
  # do a hot restart after adding new image directory
  fonts:
    - family: Klasik
      fonts:
        - asset: assets/fonts/Klasik Regular.otf
